
package Registro;

import java.text.SimpleDateFormat;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

public class ExamenLab5P2_JafetHou extends javax.swing.JFrame {

    // FILA 2, ASIENTO 14
    public static ArrayList<Personas> persona = new ArrayList<>();
    
    public ExamenLab5P2_JafetHou() {
                
        initComponents();
        
        persona.add(new empleados("Ingeniero en biomedica", "oficinista", 3, "Jose", "Cruz", "papepi", new Date(1996, 7, 19), "M", "Fransisco Morazan", ""));
        persona.add(new Civiles("Tulio", "Sevo", "contra", new Date(2005, 11, 19), "M", "Cortes", ""));
        
        DefaultComboBoxModel idcb = (DefaultComboBoxModel) cb_identidad.getModel();
        idcb.addElement(persona.get(1).getIdentidad());
        
        
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestionEmple = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jl_bienvenidoEmple = new javax.swing.JLabel();
        jb_CerrarEmple = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cb_identidad = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        tf_ModiNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_ModiAppellido = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_ModiContra = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cb_modisexo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cb_modidepartamento = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jb_ModificarCivil = new javax.swing.JButton();
        jc_fecha = new com.toedter.calendar.JCalendar();
        GestionCivil = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jl_bienvenidoCivil = new javax.swing.JLabel();
        jb_cerrarCivil = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_infoPer = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_TramiteNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_descripcion = new javax.swing.JTextField();
        jb_EnviarTramite = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tf_nombre = new javax.swing.JTextField();
        jb_entrar = new javax.swing.JButton();
        jb_Salir = new javax.swing.JButton();
        Tf_contra = new javax.swing.JTextField();

        GestionEmple.setBackground(new java.awt.Color(255, 255, 255));
        GestionEmple.setMinimumSize(new java.awt.Dimension(800, 600));
        GestionEmple.setModal(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bienvenido:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 50));

        jl_bienvenidoEmple.setBackground(new java.awt.Color(255, 0, 0));
        jl_bienvenidoEmple.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bienvenidoEmple.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jl_bienvenidoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 150, 50));

        jb_CerrarEmple.setBackground(new java.awt.Color(255, 0, 0));
        jb_CerrarEmple.setText("Cerrar Sesion");
        jb_CerrarEmple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CerrarEmpleMouseClicked(evt);
            }
        });
        jb_CerrarEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CerrarEmpleActionPerformed(evt);
            }
        });
        jPanel2.add(jb_CerrarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 110, 30));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Informacion de los civiles: ");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tramites:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Completo", "No. Identidad", "Fecha de nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre del Tramite", "Descripcion", "Fecha", "No. Identidad"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informacion Civiles", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Apellido");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Contrasenia ");

        tf_ModiContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ModiContraActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Sexo");

        cb_modisexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Departamento");

        cb_modidepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fransisco Morazan", "Cortes", "Comayagua" }));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Fecha de nacimiento");

        jb_ModificarCivil.setBackground(new java.awt.Color(0, 102, 153));
        jb_ModificarCivil.setText("modificar");
        jb_ModificarCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModificarCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(tf_ModiContra)
                                    .addComponent(tf_ModiNombre)
                                    .addComponent(cb_modisexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_modidepartamento, 0, 153, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_ModiAppellido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jb_ModificarCivil)
                        .addGap(87, 87, 87)
                        .addComponent(cb_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ModificarCivil)
                    .addComponent(cb_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ModiNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ModiAppellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tf_ModiContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_modisexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_modidepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Civiles", jPanel4);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 610, 370));

        javax.swing.GroupLayout GestionEmpleLayout = new javax.swing.GroupLayout(GestionEmple.getContentPane());
        GestionEmple.getContentPane().setLayout(GestionEmpleLayout);
        GestionEmpleLayout.setHorizontalGroup(
            GestionEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GestionEmpleLayout.setVerticalGroup(
            GestionEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GestionCivil.setMinimumSize(new java.awt.Dimension(800, 600));
        GestionCivil.setModal(true);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Bienvenido:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 30));

        jl_bienvenidoCivil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_bienvenidoCivil.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jl_bienvenidoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 46, 90, 40));

        jb_cerrarCivil.setBackground(new java.awt.Color(255, 0, 0));
        jb_cerrarCivil.setText("Cerrar Sesion");
        jb_cerrarCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cerrarCivilActionPerformed(evt);
            }
        });
        jPanel5.add(jb_cerrarCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 110, 40));

        jTabbedPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane3MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Informacion Personal: ");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tramites: ");

        jt_infoPer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Completo", "No. Identidad", "Fecha"
            }
        ));
        jScrollPane3.setViewportView(jt_infoPer);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre de Tramite", "Descripcion", "Fecha", "No. de Identidad"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Informacion Personal", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre:");

        tf_TramiteNombre.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Descripcion:");

        tf_descripcion.setBackground(new java.awt.Color(255, 255, 255));
        tf_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_descripcionActionPerformed(evt);
            }
        });

        jb_EnviarTramite.setBackground(new java.awt.Color(0, 102, 153));
        jb_EnviarTramite.setText("Enviar");
        jb_EnviarTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EnviarTramiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_TramiteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_EnviarTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_EnviarTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_TramiteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );

        jTabbedPane3.addTab("Gestion de Tramites", jPanel9);

        jPanel5.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 610, 380));

        javax.swing.GroupLayout GestionCivilLayout = new javax.swing.GroupLayout(GestionCivil.getContentPane());
        GestionCivil.getContentPane().setLayout(GestionCivilLayout);
        GestionCivilLayout.setHorizontalGroup(
            GestionCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionCivilLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GestionCivilLayout.setVerticalGroup(
            GestionCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Log In");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 272, 70));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 120, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Completo: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, 30));

        Tf_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 270, 30));

        jb_entrar.setBackground(new java.awt.Color(0, 51, 102));
        jb_entrar.setText("ENTRAR");
        jb_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_entrarMouseClicked(evt);
            }
        });
        jb_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 90, 30));

        jb_Salir.setBackground(new java.awt.Color(255, 0, 0));
        jb_Salir.setText("Salir");
        jb_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(jb_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, 30));

        Tf_contra.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Tf_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarActionPerformed
        
        
    }//GEN-LAST:event_jb_entrarActionPerformed

    private void jb_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_entrarMouseClicked
        
        if(Tf_nombre.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese nombre ");
            
        }else if(Tf_contra.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese contraseña");
            
        }else if(Tf_nombre.getText().contains(persona.get(0).getNombre())){
            if(Tf_nombre.getText().contains(persona.get(0).getApellido())){
                
                jl_bienvenidoEmple.setText(persona.get(0).getNombre()+" "+persona.get(0).getApellido());
                this.setVisible(false);
                GestionEmple.setVisible(true);
                
                
            }
            
        }else if(Tf_nombre.getText().contains(persona.get(1).getNombre())){
            if(Tf_nombre.getText().contains(persona.get(1).getApellido())){
                
                jl_bienvenidoCivil.setText(persona.get(1).getNombre()+" "+persona.get(1).getApellido());
                this.setVisible(false);
                GestionCivil.setVisible(true);
                GestionCivil.setLocationRelativeTo(null);
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nombre o Contraseña incorrecta");
        }
        
    }//GEN-LAST:event_jb_entrarMouseClicked

    private void jb_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jb_SalirActionPerformed

    private void jb_CerrarEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CerrarEmpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_CerrarEmpleActionPerformed

    private void jb_CerrarEmpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CerrarEmpleMouseClicked
        GestionEmple.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_CerrarEmpleMouseClicked

    private void jb_cerrarCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cerrarCivilActionPerformed
        GestionCivil.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_cerrarCivilActionPerformed

    private void tf_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_descripcionActionPerformed

    private void jb_EnviarTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EnviarTramiteActionPerformed
        if(tf_TramiteNombre.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Debe agregar nombre del tramite");
            
        }else if(tf_descripcion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe Agregar descripcion");
        }else{
            
            Date hoy = new Date();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY");
            String fechaFormateada = formato.format(hoy);
            
            //persona.add((tramites) new tramites(tf_TramiteNombre.getText(), tf_descripcion.getText(),hoy , persona.get(1).getIdentidad()));
            
        }
    }//GEN-LAST:event_jb_EnviarTramiteActionPerformed

    private void jb_ModificarCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModificarCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ModificarCivilActionPerformed

    private void tf_ModiContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ModiContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ModiContraActionPerformed

    private void jTabbedPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane3MouseClicked
        DefaultTableModel mt = new DefaultTableModel();
        String info[] = {"Nombre Completo", "No. Identidad", "Fecha"};
        mt.setColumnIdentifiers(info);
        jt_infoPer.setModel(mt);
        
        mt.addRow(new Object[]{persona.get(1).getNombre()+" "+persona.get(1).getApellido(), persona.get(1).getIdentidad(), persona.get(1).getFecha() });
        
    }//GEN-LAST:event_jTabbedPane3MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        DefaultTableModel mt = new DefaultTableModel();
        String info[] = {"Nombre Completo", "No. Identidad", "Fecha de nacimiento"};
        mt.setColumnIdentifiers(info);
        jTable1.setModel(mt);
        
        mt.addRow(new Object[]{persona.get(1).getNombre()+" "+persona.get(1).getApellido(), persona.get(1).getIdentidad(), persona.get(1).getFecha() });
        
        DefaultTableModel tr = new DefaultTableModel();
        String trami[] = {"Nombre Tramite", "Descripcion", "Fecha", "No. Identidad"};
        tr.setColumnIdentifiers(trami);
        jTable2.setModel(tr);
        
        Civiles personaNV = new Civiles();
        //personaNV = persona.get(1);
        
        
        //tr.addRow((Civiles)persona.get(1).);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenLab5P2_JafetHou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenLab5P2_JafetHou().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog GestionCivil;
    private javax.swing.JDialog GestionEmple;
    private javax.swing.JTextField Tf_contra;
    private javax.swing.JTextField Tf_nombre;
    private javax.swing.JComboBox<String> cb_identidad;
    private javax.swing.JComboBox<String> cb_modidepartamento;
    private javax.swing.JComboBox<String> cb_modisexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton jb_CerrarEmple;
    private javax.swing.JButton jb_EnviarTramite;
    private javax.swing.JButton jb_ModificarCivil;
    private javax.swing.JButton jb_Salir;
    private javax.swing.JButton jb_cerrarCivil;
    private javax.swing.JButton jb_entrar;
    private com.toedter.calendar.JCalendar jc_fecha;
    private javax.swing.JLabel jl_bienvenidoCivil;
    private javax.swing.JLabel jl_bienvenidoEmple;
    private javax.swing.JTable jt_infoPer;
    private javax.swing.JTextField tf_ModiAppellido;
    private javax.swing.JTextField tf_ModiContra;
    private javax.swing.JTextField tf_ModiNombre;
    private javax.swing.JTextField tf_TramiteNombre;
    private javax.swing.JTextField tf_descripcion;
    // End of variables declaration//GEN-END:variables
}
